# Sample usage of reusable.yml in Debug build for backend team
name: CI Debug Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  debug:
    uses: ./.github/workflows/reusable.yml
    with:
      configuration: Debug
      dotnet_version: "9.0.x"
      project_path: MVCSampleApp/MVCSampleApp.csproj
      unit_test_project_path: MVCSampleApp.Tests/MVCSampleApp.Tests.csproj # example csproj file path
      ui_test_project_path: MVCSampleApp.UITests/MVCSampleApp.UITests.csproj # example csproj file path
      run_unit_tests: true
      run_ui_tests: true
      run_static_analysis: true
