# Sample usage of reusable.yml in Release build for backend team
name: CI Release Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/reusable.yml
    with:
      configuration: Release
      dotnet_version: "9.0.x"
      project_path: MVCSampleApp/MVCSampleApp.csproj # example csproj file path
      run_unit_tests: false
      run_ui_tests: false
      run_static_analysis: false
